### ISSUE TITLE
Feature Request: Support for Returning Types & console.log String Value

### ISSUE THREAD

**Issue by reggi** [yamadapc/jsdoctest#16]
If you have a function like this.

    var foo = function(){}

And you log it.

    console.log(foo)

You get a print out of the object type.

    [Function]

If it's a named object.

    function foo(){}

And you log it.

    console.log(foo)

You get the print out of the object type and variable.

    [Function: foo]

Node's `console.log()` string is powered by `util.format()` So my recommendation is to support all of this in tests. By passing the result from an `@example` to `util.format()` and matching the result to the expected result from the output (ex.`// => [Function]`).

With a little regex magic it doesn't many options can be supported. `(.+):`

Ideally all of these work.

    function foo(){}
    // => [Function]
    // => [function]
    // => [Function: foo]
    // => [function: foo]
    // => [Function:foo]
    // => [function:foo]

This example is a bit superfluous because in the definition for a function the `@returns` statement declares type. Does this library use that to asset types?

However my stackoverflow posts about [Returning a object with specific property and type](http://stackoverflow.com/questions/31714259/returning-a-object-with-specific-property-and-type) would be a much better example.

I could test an object with a specific signature, like this.

operation("foo", console.log)
// => {"foo": [Function]}

@yamadapc What are your thoughts?

**Comment by reggi** [comment]
I just checked even if you specify a return type you can still assert a string.

```
/**
 * Adds to numbers
 * @param  {number} a
 * @param  {number} b
 * @returns {number}
 * @example
 * add(10, 10)
 * // => "20"
 */
var add = function(a, b){
  return a + b + ""
}
```

**Comment by yamadapc** [comment]
You can `typeof s // => 'string'` or anything
