### ISSUE TITLE
Feature Request: Way to use expect, should, and assert

### ISSUE THREAD

**Issue by reggi** [yamadapc/jsdoctest#18]
I think that ultimately when it comes to a more specific test it might be ideal to trigger a comment flag to use chai outright.

```
@example
somefunction()
// chai => expect.to.have.property("hello")
```

or

```
@example
// it => should have property hello
var x = somefunction()
expect(x).to.have.property("hello")
```

**Comment by yamadapc** [comment]
ATM the planned way is to have them in scope or not use them.
