### ISSUE TITLE
The comment parser should remove <caption>s

### ISSUE THREAD

**Issue by stilist** [yamadapc/jsdoctest#27]
From the JSDoc [`@example` documentation](http://usejsdoc.org/tags-example.html):

> Examples can also be captioned using `<caption></caption>` after the @example tag.
>
>     /**
>      * Solves equations of the form a * x = b
>      * @example <caption>Example usage of method1.</caption>
>      * // returns 2
>      * globalNS.method1(5, 10);
>      * @returns {Number} Returns the value of x for the equation.
>      */

jsdoctest doesn't recognize the `<caption>`, and generates `function` bodies that include the `<caption>` text.

```shell
$ cat lib/add.js
/**
 * Adds two numbers
 * @example <caption>Test</caption>
 *    add(10, 20)
 *    // => 30
 */
function add(x, y) {
  return x + y;
}

$ "$(npm bin)/jsdoctest" --spec lib/add.js
require('should');

describe('lib/add', function() {
      describe('add()', function() {
            it('<caption>Test</caption>    add(10, 20)', function() {
                  ( < caption > Test <
                    /caption>    add(10, 20)).should.eql(30);});});});
```

**Comment by yamadapc** [comment]
Fixed in `1.6.2`. Captions are added as part of the test label, so:

```javascript
/**
 * Adds two numbers
 * @example <caption>Test</caption>
 *    add(10, 20)
 *    // => 30
 */
function add(x, y) {
  return x + y;
}

describe('lib/add', function() {
  describe('add()', function() {
    it('add(10, 20) - Test', function() {/*...*/});
  });
});
```

**Comment by yamadapc** [comment]
Run `mocha --require . test/test-file-captioned.js` to see it happen.

**Comment by stilist** [comment]
Thank you!
