### ISSUE TITLE
Semicolon insertion breaks complex examples

### ISSUE THREAD

**Issue by ianwremmel** [yamadapc/jsdoctest#28]
I'm trying to write a test that does an async action and makes some assertions about a non-deterministic result

```javascript
createResource()
  .then(function(resource) {
    assert(typeof resource.id !== 'undefined')
    return 'success';
  });
  // async => 'success'
```

This fails because jsdoctest seems to add a semicolon to the end of each line and therefore produces invalid javascript.

**Comment by yamadapc** [comment]
Mm... Could you send the full block that you're using?

**Comment by yamadapc** [comment]
I'll fix it this week. For now if you move `.then` to the `createResource` line you should be fine.

**Comment by yamadapc** [comment]
Pushed preliminary fix, going to try a more principled approach to getting this to properly work.

**Comment by ianwremmel** [comment]
awesome, thanks for the quick response!
